# Generated by Django 4.2 on 2023-09-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_productvariations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariations',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storeapp.productvariations'),
        ),
    ]
